name: 'twitter_organic_integration_tests'
version: '0.2.0'
profile: 'integration_tests'
config-version: 2

vars:
  twitter_organic_source:
    twitter_organic_account_history_identifer: "twitter_organic_account_history_data"
    twitter_organic_organic_tweet_report_identifer: "twitter_organic_organic_tweet_report_data"
    twitter_organic_tweet_identifer: "twitter_organic_tweet_data"
    twitter_organic_twitter_user_history_identifer: "twitter_organic_twitter_user_history_data"
    twitter_organic_schema: twitter_organic_integration_tests_1

models: 
  twitter_organic_source:
    +materialized: table

seeds:
  twitter_organic_integration_tests:
    twitter_organic_tweet_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    twitter_organic_organic_tweet_report_data:
      +column_types:
        organic_tweet_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
